apiVersion: v1
kind: Service
metadata:
  name: devstore-api-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: devstore-api
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30002   # fixed port for easier access