apiVersion: apps/v1
kind: Deployment
metadata:
  name: devstore-api
  namespace: default
  labels:
    app: devstore-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devstore-api
  template:
    metadata:
      labels:
        app: devstore-api
    spec:
      containers:
        - name: api
          image: 517355797272.dkr.ecr.ap-southeast-2.amazonaws.com/devstore-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000

          env:
            - name: DATABASE_URL
              value: "postgresql://devstore:devstore@postgres-service:5432/devstore"

            - name: NODE_ENV
              value: "production"

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"